// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:BaseDI.Professional.Playground.Test.Chapter.Page.Programming_1.Page_1_9_Verify_Process_12_2_1_0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Story.Programming_2.Implement_DesignPattern_Factory_Director_12_2_1_0`1.Action_1_Begin_Process~System.Threading.Tasks.Task{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~F:BaseDI.Professional.Playground.Test.State.Social_Media_.RemoteServiceVendor_Experience_The_Movement_ToFacebookPage_DataTransfer_2_3_1_0._pageEdgeVideo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_.eMethods_Programming_JSON_12_2_1_0.Extension_Read_JSON_Nodes_2_0(System.Collections.Generic.List{Newtonsoft.Json.Linq.JToken},System.String,System.String,System.Boolean)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_.eMethods_Programming_JSON_12_2_1_0.Extension_Read_JSON_Nodes_1_0(Newtonsoft.Json.Linq.JToken,System.String)~System.Collections.Generic.List{Newtonsoft.Json.Linq.JToken}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:BaseDI.Professional.Playground.Test.Chapter.Page.Programming_1.Page_1_10_End_Process_12_2_1_0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Chapter.Page.Programming_1.Page_1_10_End_Process_12_2_1_0.Step_1_2_Custom_Route_Request(System.String)~Newtonsoft.Json.Linq.JObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_.eMethods_Programming_JSON_12_2_1_0.Extension_Read_JSON_Nodes_1_1(Newtonsoft.Json.Linq.JToken,System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JToken})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_.eMethods_Programming_JSON_12_2_1_0.Extension_Read_JSON_Nodes_1_0(Newtonsoft.Json.Linq.JToken,System.String)~System.Collections.Generic.List{Newtonsoft.Json.Linq.JToken}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_1.eMethods_Programming_JSON_12_2_1_0.Extension_Read_JSON_Nodes_1_0(Newtonsoft.Json.Linq.JToken,System.String)~System.Collections.Generic.List{Newtonsoft.Json.Linq.JToken}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_1.eMethods_Programming_JSON_12_2_1_0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "namespace", Target = "~N:BaseDI.Professional.Playground.Test.Script.Programming.Extensions_1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:BaseDI.Professional.Playground.Test.Director.Advertising_1.Director_Of_Advertising_Chapter_1_1_Page_1_CreateAdvertisementForAll_Handler_1_0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "namespace", Target = "~N:BaseDI.Professional.Playground.Test.Director.Advertising_1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:BaseDI.Professional.Playground.Test.Director.Programming_1.Director_Of_Programming_Chapter_12_2_Page_1_Request_Handler_1_0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Experience_Social_Media_1.Implement_DesignPattern_Builder_Experience_2_3_1_0.Action_1_Begin_Process~System.Threading.Tasks.Task{Newtonsoft.Json.Linq.JObject}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:BaseDI.Professional.Playground.Test.Story.Programming_2.ProgrammingStudioAdministrator_MasterLeader_12_2_1_0`1.PreSetupStoryline")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:BaseDI.Professional.Experience_The_Movement_ToFacebookPage_DataTransfer_7_1_1_0_Test.Update_Client")]
