FROM alpine:edge
MAINTAINER Francisco Sales <francisco@poetic.io>

WORKDIR /app

ADD package.json /app/package.json

RUN \
  echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
  apk add --update \
  yarn nodejs nodejs-npm

ENV NODE_ENV=${NODE_ENV}
ENV REACT_APP_ENV=${REACT_APP_ENV}
RUN yarn install --production

ADD build/ /app/build
ADD dist/ /app/dist
ADD server/ /app/server
ADD src/ /app/src

EXPOSE 3000
CMD [ "yarn", "start" ]
