apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  labels:
    name: nginx-demo-nodeport-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    name: nginx-demo