replicaCount: 1
restartPolicy: Never

release:
  app: amlicom-qa
  stage: qa
  stageNamespace: amlicom-qa
  version: 1.0.0

image:
  repository: amlicontainers.azurecr.io
  tag: v1
  pullPolicy: Always

service:
  name: amlicom-qa
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30125
  protocol: TCP

podAnnotations: {}

resources: {}

nodeSelector: {}
